.\" Copyright (c) 2019, Steffen Fritz
.\"
.\" %%%LICENSE_START(GPLv2+_DOC_FULL)
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, see
.\" <http://www.gnu.org/licenses/>.
.\" %%%LICENSE_END

.TH gobagit 1 "July 2019" "version 0.4.0"
.SH NAME
gobagit
.SH SYNOPSIS
.B gobagit [OPTION] [PATH]
.SH DESCRIPTION
gobagit is a utility to work with the BagIt file system format.

BagIt is a set of hierarchical file system conventions designed to support disk-based storage and network transfer of
arbitrary digital content. A bag consists of a payload and tag files, which are metadata files intended to document the storage and transfer of the bag. A required tag file contains a manifest listing every file in the payload together with its corresponding checksum.

Bags are ideal for digital content normally kept as a collection of files. They are also well-suited to the export, for archival purposes, of content normally kept in database structures that receiving parties are unlikely to support. 


.SH FLAGS

.BR \-create\fR
        Create bag. Expects path to source directory

.BR \-fetch\fR
        Adds optional fetch file to bag. Expects path to fetch.txt file and flag manifetch

.BR \-hash\fR
        Hash algorithm used for manifest file when creating a bag

.BR \-header\fR
        Additional headers for bag-info.txt. Expects path to json file

.BR \-manifetch\fR
        Path to manifest file for optional fetch.txt file. Mandatory if fetch switch is used

.BR \-output\fR
        Output directory for bag. Used with create flag

.BR \-tagmanifest\fR
        Hash algorithm used for tag manifest file

.BR \-tar\fR
        Create a tar archive when creating a bag

.BR \-v\fR
        Verbose output

.BR \-validate\fR
        Validate bag. Expects path to bag

.BR \-version\fR
        Print version



.SH AUTHOR
Steffen Fritz <steffen@fritz.wtf>

